# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serial_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(548, 376)
        self.connect_Button = QtWidgets.QPushButton(Form)
        self.connect_Button.setGeometry(QtCore.QRect(50, 70, 81, 31))
        self.connect_Button.setObjectName("connect_Button")
        self.baud_text = QtWidgets.QLabel(Form)
        self.baud_text.setGeometry(QtCore.QRect(150, 40, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.baud_text.setFont(font)
        self.baud_text.setObjectName("baud_text")
        self.baud_List = QtWidgets.QComboBox(Form)
        self.baud_List.setGeometry(QtCore.QRect(140, 70, 101, 31))
        self.baud_List.setObjectName("baud_List")
        self.port_List = QtWidgets.QComboBox(Form)
        self.port_List.setGeometry(QtCore.QRect(260, 70, 101, 31))
        self.port_List.setObjectName("port_List")
        self.port_text = QtWidgets.QLabel(Form)
        self.port_text.setGeometry(QtCore.QRect(260, 40, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.port_text.setFont(font)
        self.port_text.setObjectName("port_text")
        self.refresh_Button = QtWidgets.QPushButton(Form)
        self.refresh_Button.setGeometry(QtCore.QRect(400, 70, 81, 31))
        self.refresh_Button.setObjectName("refresh_Button")
        self.portinfo_field = QtWidgets.QTextBrowser(Form)
        self.portinfo_field.setGeometry(QtCore.QRect(160, 140, 321, 192))
        self.portinfo_field.setObjectName("portinfo_field")
        self.portinfo_text = QtWidgets.QLabel(Form)
        self.portinfo_text.setGeometry(QtCore.QRect(60, 140, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.portinfo_text.setFont(font)
        self.portinfo_text.setObjectName("portinfo_text")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Serial COM Port Fetcher"))
        self.connect_Button.setText(_translate("Form", "Connect"))
        self.baud_text.setText(_translate("Form", "Baudrate"))
        self.port_text.setText(_translate("Form", "COM Port"))
        self.refresh_Button.setText(_translate("Form", "Refresh"))
        self.portinfo_text.setText(_translate("Form", "Port Info:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
